import type { Metadata } from "next";
import { Kanit } from 'next/font/google'
// import localFont from "next/font/local";
import "./globals.css";

import StoreProvider from "ui/store/providers/StoreProvider";
import QueryProvider from "ui/store/providers/QueryProvider"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "EXPENSESS APP",
  description: "Generated by create next app",
};

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['300','500','600']
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${kanit.className}`}>
          <StoreProvider>
            <QueryProvider>{children}</QueryProvider>
          </StoreProvider>
        </body>
    </html>
  );
}
